//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntLibContrib.Data.IBM.DB2.iSeries.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntLibContrib.Data.IBM.DB2.iSeries.Configuration.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to an Db2 database..
        /// </summary>
        internal static string Db2ConnectionDataDescription {
            get {
                return ResourceManager.GetString("Db2ConnectionDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db2 Connection.
        /// </summary>
        internal static string Db2ConnectionDataDisplayName {
            get {
                return ResourceManager.GetString("Db2ConnectionDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Db2 Connection..
        /// </summary>
        internal static string Db2ConnectionDataNameDescription {
            get {
                return ResourceManager.GetString("Db2ConnectionDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Db2ConnectionDataNameDisplayName {
            get {
                return ResourceManager.GetString("Db2ConnectionDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections to Db2 databases..
        /// </summary>
        internal static string Db2ConnectionSettingsDb2ConnectionsDataDescription {
            get {
                return ResourceManager.GetString("Db2ConnectionSettingsDb2ConnectionsDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db2 Connections.
        /// </summary>
        internal static string Db2ConnectionSettingsDb2ConnectionsDataDisplayName {
            get {
                return ResourceManager.GetString("Db2ConnectionSettingsDb2ConnectionsDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings specific to Db2 connections.
        /// </summary>
        internal static string Db2ConnectionSettingsDescription {
            get {
                return ResourceManager.GetString("Db2ConnectionSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db2 Connection Settings.
        /// </summary>
        internal static string Db2ConnectionSettingsDisplayName {
            get {
                return ResourceManager.GetString("Db2ConnectionSettingsDisplayName", resourceCulture);
            }
        }
    }
}
